[33mWARNING [0m urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8d012b7128>: Failed to establish a new connection: [Errno 111] Connection refused',)': /wd/hub/session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8d012b73c8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /wd/hub/session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:781 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8d012b7a58>: Failed to establish a new connection: [Errno 111] Connection refused',)': /wd/hub/session